import Foundation

enum Verlag: String, CaseIterable {
    case egmont = "Egmont Manga"
    case planet = "Planet Manga"
    case tokyopop = "Tokyopop"
    case carlsen = "Carlsen Manga"
    case altraverse = "Altraverse"
    case kaze = "Kaze Manga"
    case panini = "Panini Manga"
    case cult = "Manga Cult"
    case shueisha = "Shueisha"
    case heyne = "Heyne Manga"
    case schreiber = "Schreiber & Leser"
    case schwarzer = "Schwarzer Turm"
    case butter = "Butter & Cream"
    case j = "J-Store"
    case cursed = "Cursed Side"
    case izm = "Studio-izm"
    case fire = "Fireangels"
    case sutra = "MangaSutra"
    case epsilon = "Epsilon Verlag"
    case dojinshi = "Dojinshi"
    case unknown = "-"
}
